name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}
  schedule:
    - cron: 02 03 * * *
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: test/playwright/report/
        retention-days: 30
    env:
      CI: true
      LT_ACCESS_KEY: ${{ secrets.LAMBDATEST_USERNAME }}
      LT_USERNAME: ${{ secrets.LAMBDATEST_ACCESSKEY }}
      ENVIRONMENT: ${{github.ref}}
